type: agent
parameters:
  - id: md6TfhWW8K4KjDUtWaFCK
    key: needReview
    type: boolean
  - id: EMqIUn7ScElctnFFSLNmG
    key: labels
    type: string
  - id: vQGSADvuog7K6pLrDSc8N
    key: data
    type: source
    source:
      variableFrom: tool
      agent:
        projectId: "475837658589822976"
        id: 20240806100101-6TQsv6
        from: assistant
  - id: zYqnLbiN6Dyha0DbTxePn
    key: translates
    type: source
    source:
      variableFrom: tool
      agent:
        projectId: "475837658589822976"
        id: 20240806103620-Jb5qkf
        from: assistant
        parameters:
          title: "{{ data.title }}"
          content: "{{ data.content }}"
  - id: PD7ZJaRX8jIkkhUTDHp9p
    key: upload
    type: source
    source:
      variableFrom: tool
      agent:
        projectId: "475837658589822976"
        id: 20240807150429-JoozZB
        from: assistant
        parameters:
          translates: "{{ translates }}"
          labels: "{{ labels }}"
          needReview: "{{ needReview }}"
          title: "{{ data.title }}"
          content: "{{ data.content }}"
          image: "{{ data.image }}"
    hidden: false
prompts:
  XxrRWk2WtHU7zbThXH-87:
    index: 0
    data:
      type: message
      data:
        id: XxrRWk2WtHU7zbThXH-87
        role: user
        content: "{{ result }}"
outputVariables:
  - id: HneG50x9aI4iviUxDo6Gx
    name: result
    from:
      type: input
      id: PD7ZJaRX8jIkkhUTDHp9p
id: 20240807115154-UahADD
createdAt: 2024-08-06T01:31:39.745Z
updatedAt: 2024-08-06T01:31:39.745Z
createdBy: z2qaBKnrTUAobCcqGMbqAMFW5WHpYzL3Kub2D
updatedBy: z2qaBKnrTUAobCcqGMbqAMFW5WHpYzL3Kub2D
name: 生成数据(OpenAPI)
code: |-
  if(result.status ==='success') {
    return "成功"
  }

  return "失败"
model: gpt-4o-mini
